import operator
from functools import reduce

import listparser

# change the demo recipe to what you want to use
_recipes = {
    "web3_news": {
        "urls": [
            "https://mirror.xyz/cavin.eth/feed/atom",
            "https://mirror.xyz/curiousjoe.eth/feed/atom",
            "https://mirror.xyz/maskpad.eth/feed/atom",
            "https://mirror.xyz/0xCc964360fBFE6CD1E9a9240bcFE959199409335E/feed/atom",
            "https://mirror.xyz/shibdao.eth/feed/atom",
            "https://medium.com/feed/@bitalkforu",
            "https://mirror.xyz/guojing.eth/feed/atom",
            "https://mirror.xyz/0x65F9C4a20Dd2E32f8673FD6dc3106Db1443AE4af/feed/atom",
            "https://mirror.xyz/jojonas1.eth/feed/atom",
            "https://mirror.xyz/cryptosome.eth/feed/atom",
            "https://mirror.xyz/nikokvcs.eth/feed/atom",
            "https://mirror.xyz/mnhsu.eth/feed/atom",
            "https://mirror.xyz/nomadlab.eth/feed/atom",
            "https://mirror.xyz/0x262F0b029693F81fa0b7aAFceAe1F5cfCDaE7d82/feed/atom",
            "https://mirror.xyz/l1ning.eth/feed/atom",
            "https://mirror.xyz/peopleweb.eth/feed/atom",
            "https://mirror.xyz/0xb6C61A1DeDDfAaFe7ef9B26ae74Fb71afd5e9E4B/feed/atom",
            "https://mirror.xyz/ethvip.eth/feed/atom",
            "https://mirror.xyz/zlexdl.eth/feed/atom",
            "https://medium.com/feed/@jianshubiji",
            "https://bankless.substack.com/feed/",
            "https://medium.com/feed/@cryptohayes",
            "https://shawn.mirror.xyz/feed/atom",
            "https://mirror.xyz/0xfe1aBf3e20AC87f848DF8cA0C182CC62606378A1/feed/atom",
            "https://mirror.xyz/btcsgj.eth/feed/atom",
            "https://mirror.xyz/cryptocishanjia.eth/feed/atom",
            "https://mirror.xyz/bimeng.eth/feed/atom",
            "https://mirror.xyz/dao4ever.eth/feed/atom",
            "https://mirror.xyz/0x6ACb28b8FF66AbAB7959355697fAaF348099996b/feed/atom",
            "https://mirror.xyz/0xE43a21Ee76b591fe6E479da8a8a388FCfea6F77F/feed/atom",
            "https://mirror.xyz/foresightnews.eth/feed/atom",
            "https://mirror.xyz/0x7d36E06251E8376d7194147D9D26214566FAc47D/feed/atom",
            "https://medium.com/feed/@b1995",
            "https://mirror.xyz/0x0E58bB9795a9D0F065e3a8Cc2aed2A63D6977d8A/feed/atom",
            "https://mirror.xyz/0xcF372762FE08682528Cba6BfA367A768d7b0afB4/feed/atom",
            "https://mirror.xyz/snapfingersdao.eth/feed/atom",
            "https://mirror.xyz/0x1E2410217C2071046194372Edfd12540b9308029/feed/atom",
            "https://mirror.xyz/0xCc964360fBFE6CD1E9a9240bcFE959199409335E/feed/atom",
            "https://mirror.xyz/0xE901d6E73ed520a27cE01a07f938181973cFE098/feed/atom",
            "https://mirror.xyz/mintventures.eth/feed/atom",
            "https://mirror.xyz/0xABae923874F05e922A22932d8d2117ffE627212d/feed/atom",
            "https://mirror.xyz/tannhauser2049.eth/feed/atom",
            "https://c.mirror.xyz/feed/atom",
        ],
        "filters": [
            {
                "in_seconds": 3600 * 24 * 3,
            },
        ],
    },
    "web3_news_mirror": {
        "urls": [
           	"https://mirror.xyz/cavin.eth/feed/atom",
            "https://mirror.xyz/curiousjoe.eth/feed/atom",
            "https://mirror.xyz/0xCc964360fBFE6CD1E9a9240bcFE959199409335E/feed/atom",
            "https://mirror.xyz/shibdao.eth/feed/atom",
            "https://mirror.xyz/0x65F9C4a20Dd2E32f8673FD6dc3106Db1443AE4af/feed/atom",
            "https://mirror.xyz/jojonas1.eth/feed/atom",
            "https://mirror.xyz/mnhsu.eth/feed/atom",
            "https://mirror.xyz/nomadlab.eth/feed/atom",
            "https://mirror.xyz/l1ning.eth/feed/atom",
            "https://mirror.xyz/0xb6C61A1DeDDfAaFe7ef9B26ae74Fb71afd5e9E4B/feed/atom",
            "https://mirror.xyz/ethvip.eth/feed/atom",
            "https://mirror.xyz/zlexdl.eth/feed/atom",
            "https://shawn.mirror.xyz/feed/atom",
            "https://mirror.xyz/bimeng.eth/feed/atom",
            "https://mirror.xyz/0x6ACb28b8FF66AbAB7959355697fAaF348099996b/feed/atom",
            "https://mirror.xyz/0xE43a21Ee76b591fe6E479da8a8a388FCfea6F77F/feed/atom",
            "https://mirror.xyz/snapfingersdao.eth/feed/atom",
            "https://mirror.xyz/mintventures.eth/feed/atom",
            "https://mirror.xyz/0xABae923874F05e922A22932d8d2117ffE627212d/feed/atom",
            "https://mirror.xyz/nonem.eth/feed/atom",
            "https://mirror.xyz/oxpepper.eth/feed/atom",
            "https://ath.mirror.xyz/feed/atom",
            "https://buidl.mirror.xyz/feed/atom",
            "https://coinvise.mirror.xyz/feed/atom",
            "https://forefront.mirror.xyz/feed/atom",
            "https://k.mirror.xyz/feed/atom",
            "https://musicx.mirror.xyz/feed/atom",
            "https://society.mirror.xyz/feed/atom",
            "https://stark.mirror.xyz/feed/atom",
            "https://mirror.xyz/0xemperor.eth/feed/atom",
            "https://mirror.xyz/11223.eth/feed/atom",
            "https://mirror.xyz/3344521.eth/feed/atom",
            "https://mirror.xyz/98kdao.eth/feed/atom",
            "https://mirror.xyz/a10.eth/feed/atom",
            "https://mirror.xyz/antisystem.eth/feed/atom",
            "https://mirror.xyz/atiris.eth/feed/atom",
            "https://mirror.xyz/bimeng.eth/feed/atom",
            "https://mirror.xyz/bitwhalecapital.eth/feed/atom",
            "https://mirror.xyz/btcdayu.eth/feed/atom",
            "https://mirror.xyz/bttb.eth/feed/atom",
            "https://mirror.xyz/chainhouse.eth/feed/atom",
            "https://mirror.xyz/cryptolich.eth/feed/atom",
            "https://mirror.xyz/cryptouf.eth/feed/atom",
            "https://mirror.xyz/cwweb3.eth/feed/atom",
            "https://mirror.xyz/daomstr.eth/feed/atom",
            "https://mirror.xyz/daoone.eth/feed/atom",
            "https://mirror.xyz/darkhorseclub.eth/feed/atom",
            "https://mirror.xyz/denze.eth/feed/atom",
            "https://mirror.xyz/dere.eth/feed/atom",
            "https://mirror.xyz/dfarm.eth/feed/atom",
            "https://mirror.xyz/duynguyen96.eth/feed/atom",
            "https://mirror.xyz/epowell101.eth/feed/atom",
            "https://mirror.xyz/ethereumcn.eth/feed/atom",
            "https://mirror.xyz/guoyu.eth/feed/atom",
            "https://mirror.xyz/harichen.eth/feed/atom",
            "https://mirror.xyz/harvardblockchain.eth/feed/atom",
            "https://mirror.xyz/homepod.eth/feed/atom",
            "https://mirror.xyz/jackofcrypto.eth/feed/atom",
            "https://mirror.xyz/jayjiang.eth/feed/atom",
            "https://mirror.xyz/jtsong.eth/feed/atom",
            "https://mirror.xyz/juliamaltby.eth/feed/atom",
            "https://mirror.xyz/kishans.eth/feed/atom",
            "https://mirror.xyz/kurtpan.eth/feed/atom",
            "https://mirror.xyz/l1ning.eth/feed/atom",
            "https://mirror.xyz/maithao.eth/feed/atom",
            "https://mirror.xyz/mintventures.eth/feed/atom",
            "https://mirror.xyz/mnhsu.eth/feed/atom",
            "https://mirror.xyz/msfew.eth/feed/atom",
            "https://mirror.xyz/orangex.eth/feed/atom",
            "https://mirror.xyz/owoowo.eth/feed/atom",
            "https://mirror.xyz/penny777.eth/feed/atom",
            "https://mirror.xyz/raccooncrypto.eth/feed/atom",
            "https://mirror.xyz/ryangtanaka.eth/feed/atom",
            "https://mirror.xyz/shibdao.eth/feed/atom",
            "https://mirror.xyz/silhouette114.eth/feed/atom",
            "https://mirror.xyz/sleepy0x13.eth/feed/atom",
            "https://mirror.xyz/snapfingersdao.eth/feed/atom",
            "https://mirror.xyz/themeaganloyst.eth/feed/atom",
            "https://mirror.xyz/tomu.eth/feed/atom",
            "https://mirror.xyz/twodam.eth/feed/atom",
            "https://mirror.xyz/warpsound.eth/feed/atom",
            "https://mirror.xyz/wherefi.eth/feed/atom",
            "https://mirror.xyz/wildchina.eth/feed/atom",
            "https://mirror.xyz/xing824.eth/feed/atom",
            "https://mirror.xyz/xunfa.eth/feed/atom",
            "https://mirror.xyz/yanzu.eth/feed/atom",
            "https://mirror.xyz/yourairdrop.eth/feed/atom",
            "https://mirror.xyz/yufly.eth/feed/atom",
            "https://mirror.xyz/yunzi.eth/feed/atom",
            "https://mirror.xyz/owenzhang.eth/feed/atom",
        ],
        "filters": [
            {
                "in_seconds": 3600 * 24 * 3,
            },
        ],
    },
    "web3_news_medium": {
        "urls": [
            "https://medium.com/feed/@bitalkforu",
            "https://medium.com/feed/@jianshubiji",
            "https://medium.com/feed/@cryptohayes",
            "https://medium.com/feed/@b1995",
            "https://medium.com/feed/@ntmoney",
            "https://medium.com/feed/@jhSMRT",
        ],
        "filters": [
            {
                "in_seconds": 3600 * 24 * 3,
            },
        ],
    },
    "web3_massive_news": {
        "urls": [
            "https://mirror.xyz/alexalombardo.eth/feed/atom",
            "https://mirror.xyz/amanm.eth/feed/atom",
            "https://mirror.xyz/armota.eth/feed/atom",
            "https://mirror.xyz/carolinarojas.eth/feed/atom",
            "https://mirror.xyz/cryptonatrix.eth/feed/atom",
            "https://mirror.xyz/eiji.eth/feed/atom",
            "https://mirror.xyz/elimy.eth/feed/atom",
            "https://mirror.xyz/jarrodbarnes.eth/feed/atom",
            "https://mirror.xyz/lillichoung.eth/feed/atom",
            "https://mirror.xyz/makemyrecordskp.eth/feed/atom",
            "https://mirror.xyz/matthewiles.eth/feed/atom",
            "https://mirror.xyz/naz.eth/feed/atom",
            "https://mirror.xyz/niz.eth/feed/atom",
            "https://mirror.xyz/nonem.eth/feed/atom",
            "https://mirror.xyz/oxpepper.eth/feed/atom",
            "https://mirror.xyz/pay.eth/feed/atom",
            "https://mirror.xyz/pet3rpan.eth/feed/atom",
            "https://mirror.xyz/poptones.eth/feed/atom",
            "https://mirror.xyz/rohaan.eth/feed/atom",
            "https://mirror.xyz/rwx.eth/feed/atom",
            "https://mirror.xyz/shinjurou.eth/feed/atom",
            "https://mirror.xyz/tfleming.eth/feed/atom",
            "https://mirror.xyz/tiyo.eth/feed/atom",
            "https://aave.mirror.xyz/feed/atom",
            "https://aavegrants.mirror.xyz/feed/atom",
            "https://alexkroeger.mirror.xyz/feed/atom",
            "https://anett.mirror.xyz/feed/atom",
            "https://ath.mirror.xyz/feed/atom",
            "https://avc.mirror.xyz/feed/atom",
            "https://banklessdao.mirror.xyz/feed/atom",
            "https://buidl.mirror.xyz/feed/atom",
            "https://calblockchain.mirror.xyz/feed/atom",
            "https://city.mirror.xyz/feed/atom",
            "https://club.mirror.xyz/feed/atom",
            "https://coinvise.mirror.xyz/feed/atom",
            "https://coopahtroopa.mirror.xyz/feed/atom",
            "https://creators.mirror.xyz/feed/atom",
            "https://cryptocoven.mirror.xyz/feed/atom",
            "https://dao.mirror.xyz/feed/atom",
            "https://daohaus.mirror.xyz/feed/atom",
            "https://dev.mirror.xyz/feed/atom",
            "https://diamond.mirror.xyz/feed/atom",
            "https://echo.mirror.xyz/feed/atom",
            "https://ed3.mirror.xyz/feed/atom",
            "https://ethtaipei.mirror.xyz/feed/atom",
            "https://forefront.mirror.xyz/feed/atom",
            "https://fwb.mirror.xyz/feed/atom",
            "https://gallery.mirror.xyz/feed/atom",
            "https://haole.mirror.xyz/feed/atom",
            "https://impossible.mirror.xyz/feed/atom",
            "https://jmj.mirror.xyz/feed/atom",
            "https://jo7.mirror.xyz/feed/atom",
            "https://jpg.mirror.xyz/feed/atom",
            "https://k.mirror.xyz/feed/atom",
            "https://launch.mirror.xyz/feed/atom",
            "https://mcdao.mirror.xyz/feed/atom",
            "https://mclub.mirror.xyz/feed/atom",
            "https://meta.mirror.xyz/feed/atom",
            "https://musicx.mirror.xyz/feed/atom",
            "https://onboard.mirror.xyz/feed/atom",
            "https://orca.mirror.xyz/feed/atom",
            "https://pp.mirror.xyz/feed/atom",
            "https://pseudotheos.mirror.xyz/feed/atom",
            "https://pubdao.mirror.xyz/feed/atom",
            "https://rara.mirror.xyz/feed/atom",
            "https://regan.mirror.xyz/feed/atom",
            "https://reservoir.mirror.xyz/feed/atom",
            "https://sarah.mirror.xyz/feed/atom",
            "https://scott.mirror.xyz/feed/atom",
            "https://shawn.mirror.xyz/feed/atom",
            "https://society.mirror.xyz/feed/atom",
            "https://sound.mirror.xyz/feed/atom",
            "https://stark.mirror.xyz/feed/atom",
            "https://station.mirror.xyz/feed/atom",
            "https://mirror.xyz/0xbi.eth/feed/atom",
            "https://mirror.xyz/0xemperor.eth/feed/atom",
            "https://mirror.xyz/0xgirls.eth/feed/atom",
            "https://mirror.xyz/0xleb.eth/feed/atom",
            "https://mirror.xyz/0xproductgal.eth/feed/atom",
            "https://mirror.xyz/0xruby.eth/feed/atom",
            "https://mirror.xyz/0xsodalight.eth/feed/atom",
            "https://mirror.xyz/0xsoros.eth/feed/atom",
            "https://mirror.xyz/0xsouppp.eth/feed/atom",
            "https://mirror.xyz/11223.eth/feed/atom",
            "https://mirror.xyz/16668.eth/feed/atom",
            "https://mirror.xyz/1satoshi.eth/feed/atom",
            "https://mirror.xyz/1todamoon.eth/feed/atom",
            "https://mirror.xyz/3344521.eth/feed/atom",
            "https://mirror.xyz/98kdao.eth/feed/atom",
            "https://mirror.xyz/a10.eth/feed/atom",
            "https://mirror.xyz/aean.eth/feed/atom",
            "https://mirror.xyz/akashanhu.eth/feed/atom",
            "https://mirror.xyz/alejandrocano.eth/feed/atom",
            "https://mirror.xyz/alexandrasukin.eth/feed/atom",
            "https://mirror.xyz/almeta.eth/feed/atom",
            "https://mirror.xyz/almndbtr.eth/feed/atom",
            "https://mirror.xyz/anpay.eth/feed/atom",
            "https://mirror.xyz/antisystem.eth/feed/atom",
            "https://mirror.xyz/arbestor.eth/feed/atom",
            "https://mirror.xyz/aretha-ahtera.eth/feed/atom",
            "https://mirror.xyz/atiris.eth/feed/atom",
            "https://mirror.xyz/barniker.eth/feed/atom",
            "https://mirror.xyz/bayesyy.eth/feed/atom",
            "https://mirror.xyz/beeradley.eth/feed/atom",
            "https://mirror.xyz/benchoong.eth/feed/atom",
            "https://mirror.xyz/bimeng.eth/feed/atom",
            "https://mirror.xyz/bitcoinfreetalk.eth/feed/atom",
            "https://mirror.xyz/bitwhalecapital.eth/feed/atom",
            "https://mirror.xyz/blocktv.eth/feed/atom",
            "https://mirror.xyz/blog.standard-crypto.eth/feed/atom",
            "https://mirror.xyz/bmorphism.eth/feed/atom",
            "https://mirror.xyz/bobaepicure.eth/feed/atom",
            "https://mirror.xyz/brocke.eth/feed/atom",
            "https://mirror.xyz/brunny.eth/feed/atom",
            "https://mirror.xyz/bscone.eth/feed/atom",
            "https://mirror.xyz/btcdayu.eth/feed/atom",
            "https://mirror.xyz/btcsgj.eth/feed/atom",
            "https://mirror.xyz/bttb.eth/feed/atom",
            "https://mirror.xyz/bybitcoin.eth/feed/atom",
            "https://mirror.xyz/camoufly.eth/feed/atom",
            "https://mirror.xyz/canin.eth/feed/atom",
            "https://mirror.xyz/canoncurry.eth/feed/atom",
            "https://mirror.xyz/cavin.eth/feed/atom",
            "https://mirror.xyz/cgunn.eth/feed/atom",
            "https://mirror.xyz/chainhouse.eth/feed/atom",
            "https://mirror.xyz/chamm.eth/feed/atom",
            "https://mirror.xyz/chessmaster2077.eth/feed/atom",
            "https://mirror.xyz/chibingmi.eth/feed/atom",
            "https://mirror.xyz/chinakungfu.eth/feed/atom",
            "https://mirror.xyz/cjhzr.eth/feed/atom",
            "https://mirror.xyz/clemlaflemme.eth/feed/atom",
            "https://mirror.xyz/cmurray.eth/feed/atom",
            "https://mirror.xyz/cnfeat.eth/feed/atom",
            "https://mirror.xyz/conanxin.eth/feed/atom",
            "https://mirror.xyz/cosmohm.eth/feed/atom",
            "https://mirror.xyz/coumarin.eth/feed/atom",
            "https://mirror.xyz/crisgarner.eth/feed/atom",
            "https://mirror.xyz/cryptocamus.eth/feed/atom",
            "https://mirror.xyz/cryptocishanjia.eth/feed/atom",
            "https://mirror.xyz/cryptocommons.eth/feed/atom",
            "https://mirror.xyz/cryptodesigner.eth/feed/atom",
            "https://mirror.xyz/cryptolich.eth/feed/atom",
            "https://mirror.xyz/cryptolunatic.eth/feed/atom",
            "https://mirror.xyz/cryptosome.eth/feed/atom",
            "https://mirror.xyz/cryptostats.eth/feed/atom",
            "https://mirror.xyz/cryptouf.eth/feed/atom",
            "https://mirror.xyz/curiousjoe.eth/feed/atom",
            "https://mirror.xyz/cwweb3.eth/feed/atom",
            "https://mirror.xyz/cyberlab.eth/feed/atom",
            "https://mirror.xyz/daeshawn.eth/feed/atom",
            "https://mirror.xyz/dagan.eth/feed/atom",
            "https://mirror.xyz/dalaoge.eth/feed/atom",
            "https://mirror.xyz/dao4ever.eth/feed/atom",
            "https://mirror.xyz/daomstr.eth/feed/atom",
            "https://mirror.xyz/daoone.eth/feed/atom",
            "https://mirror.xyz/dappchaser.eth/feed/atom",
            "https://mirror.xyz/darkhorseclub.eth/feed/atom",
            "https://mirror.xyz/dataalways.eth/feed/atom",
            "https://mirror.xyz/dd0sxx.eth/feed/atom",
            "https://mirror.xyz/debell.eth/feed/atom",
            "https://mirror.xyz/deepdao.eth/feed/atom",
            "https://mirror.xyz/deflance.eth/feed/atom",
            "https://mirror.xyz/denze.eth/feed/atom",
            "https://mirror.xyz/dere.eth/feed/atom",
            "https://mirror.xyz/derked.eth/feed/atom",
            "https://mirror.xyz/dfarm.eth/feed/atom",
            "https://mirror.xyz/dhaiwat.eth/feed/atom",
            "https://mirror.xyz/dill.eth/feed/atom",
            "https://mirror.xyz/doomsdayx.eth/feed/atom",
            "https://mirror.xyz/doorvesh.eth/feed/atom",
            "https://mirror.xyz/dotmusic.eth/feed/atom",
            "https://mirror.xyz/dreamindream.eth/feed/atom",
            "https://mirror.xyz/droplist.eth/feed/atom",
            "https://mirror.xyz/duckweed.eth/feed/atom",
            "https://mirror.xyz/duloti-peopledao.eth/feed/atom",
            "https://mirror.xyz/durbin.eth/feed/atom",
            "https://mirror.xyz/duynguyen96.eth/feed/atom",
            "https://mirror.xyz/dyohu.eth/feed/atom",
            "https://mirror.xyz/eastwing.eth/feed/atom",
            "https://mirror.xyz/ellis28.eth/feed/atom",
            "https://mirror.xyz/emilyzh.eth/feed/atom",
            "https://mirror.xyz/epowell101.eth/feed/atom",
            "https://mirror.xyz/ericakang.eth/feed/atom",
            "https://mirror.xyz/ericet.eth/feed/atom",
            "https://mirror.xyz/ethereumcn.eth/feed/atom",
            "https://mirror.xyz/ethvip.eth/feed/atom",
            "https://mirror.xyz/ethzerox.eth/feed/atom",
            "https://mirror.xyz/exploring.eth/feed/atom",
            "https://mirror.xyz/fabrizio.eth/feed/atom",
            "https://mirror.xyz/fanxia.eth/feed/atom",
            "https://mirror.xyz/fdd.eth/feed/atom",
            "https://mirror.xyz/foresightnews.eth/feed/atom",
            "https://mirror.xyz/fraserbell.eth/feed/atom",
            "https://mirror.xyz/gaobenpeng.eth/feed/atom",
            "https://mirror.xyz/giantbin.eth/feed/atom",
            "https://mirror.xyz/gmruby.eth/feed/atom",
            "https://mirror.xyz/godblesschinacapital.eth/feed/atom",
            "https://mirror.xyz/guill.eth/feed/atom",
            "https://mirror.xyz/guoyu.eth/feed/atom",
            "https://mirror.xyz/guwo1213.eth/feed/atom",
            "https://mirror.xyz/haole.eth/feed/atom",
            "https://mirror.xyz/haowi.eth/feed/atom",
            "https://mirror.xyz/harichen.eth/feed/atom",
            "https://mirror.xyz/harivel.eth/feed/atom",
            "https://mirror.xyz/harvardblockchain.eth/feed/atom",
            "https://mirror.xyz/hbinvest.eth/feed/atom",
            "https://mirror.xyz/heartsignal.eth/feed/atom",
            "https://mirror.xyz/highvibenetwork.eth/feed/atom",
            "https://mirror.xyz/hinterland.eth/feed/atom",
            "https://mirror.xyz/hixxx.eth/feed/atom",
            "https://mirror.xyz/holedao.eth/feed/atom",
            "https://mirror.xyz/homepod.eth/feed/atom",
            "https://mirror.xyz/huangyouhua.eth/feed/atom",
            "https://mirror.xyz/huhuyoyo.eth/feed/atom",
            "https://mirror.xyz/huoxing24.eth/feed/atom",
            "https://mirror.xyz/ianyin.eth/feed/atom",
            "https://mirror.xyz/impossibleresearch.eth/feed/atom",
            "https://mirror.xyz/iseven.eth/feed/atom",
            "https://mirror.xyz/itamarg.eth/feed/atom",
            "https://mirror.xyz/jackofcrypto.eth/feed/atom",
            "https://mirror.xyz/jacobwei.eth/feed/atom",
            "https://mirror.xyz/jakepimental.eth/feed/atom",
            "https://mirror.xyz/jasminexu.eth/feed/atom",
            "https://mirror.xyz/jasonz.eth/feed/atom",
            "https://mirror.xyz/jayjiang.eth/feed/atom",
            "https://mirror.xyz/jerry1105.eth/feed/atom",
            "https://mirror.xyz/jhj567.eth/feed/atom",
            "https://mirror.xyz/jmcook.eth/feed/atom",
            "https://mirror.xyz/jmo.eth/feed/atom",
            "https://mirror.xyz/joaxap.eth/feed/atom",
            "https://mirror.xyz/joelone.eth/feed/atom",
            "https://mirror.xyz/johnshen.eth/feed/atom",
            "https://mirror.xyz/jpangelle.eth/feed/atom",
            "https://mirror.xyz/jrm.eth/feed/atom",
            "https://mirror.xyz/jrocki.eth/feed/atom",
            "https://mirror.xyz/jtsong.eth/feed/atom",
            "https://mirror.xyz/juliamaltby.eth/feed/atom",
            "https://mirror.xyz/juliancanderson.eth/feed/atom",
            "https://mirror.xyz/jupiterverse.eth/feed/atom",
            "https://mirror.xyz/justinemoore.eth/feed/atom",
            "https://mirror.xyz/kain.eth/feed/atom",
            "https://mirror.xyz/kalico.eth/feed/atom",
            "https://mirror.xyz/kayf.eth/feed/atom",
            "https://mirror.xyz/keade.eth/feed/atom",
            "https://mirror.xyz/kennana.eth/feed/atom",
            "https://mirror.xyz/kingson.eth/feed/atom",
            "https://mirror.xyz/kirio.eth/feed/atom",
            "https://mirror.xyz/kishans.eth/feed/atom",
            "https://mirror.xyz/koutsaplis.eth/feed/atom",
            "https://mirror.xyz/kroos.eth/feed/atom",
            "https://mirror.xyz/kurtpan.eth/feed/atom",
            "https://mirror.xyz/l1ning.eth/feed/atom",
            "https://mirror.xyz/leemartin.eth/feed/atom",
            "https://mirror.xyz/lensprotocol.eth/feed/atom",
            "https://mirror.xyz/leosagan.eth/feed/atom",
            "https://mirror.xyz/lequd.eth/feed/atom",
            "https://mirror.xyz/level6.eth/feed/atom",
            "https://mirror.xyz/liangfenxiaodao.eth/feed/atom",
            "https://mirror.xyz/lightbird.eth/feed/atom",
            "https://mirror.xyz/lingyanxiao.eth/feed/atom",
            "https://mirror.xyz/littleflyingpiggy.eth/feed/atom",
            "https://mirror.xyz/loedn.eth/feed/atom",
            "https://mirror.xyz/lorenhuang.eth/feed/atom",
            "https://mirror.xyz/lstephanian.eth/feed/atom",
            "https://mirror.xyz/luckstar.eth/feed/atom",
            "https://mirror.xyz/luckylion.eth/feed/atom",
            "https://mirror.xyz/lwsnbaker.eth/feed/atom",
            "https://mirror.xyz/m0zrat.eth/feed/atom",
            "https://mirror.xyz/maddiegoldberg.eth/feed/atom",
            "https://mirror.xyz/madhavanmalolan.eth/feed/atom",
            "https://mirror.xyz/maithao.eth/feed/atom",
            "https://mirror.xyz/manther.eth/feed/atom",
            "https://mirror.xyz/maocheng.eth/feed/atom",
            "https://mirror.xyz/marymaguire.eth/feed/atom",
            "https://mirror.xyz/maskpad.eth/feed/atom",
            "https://mirror.xyz/masterpunk.eth/feed/atom",
            "https://mirror.xyz/mattdesl.eth/feed/atom",
            "https://mirror.xyz/mergod.eth/feed/atom",
            "https://mirror.xyz/miaomiao1688.eth/feed/atom",
            "https://mirror.xyz/michaelg.eth/feed/atom",
            "https://mirror.xyz/mikelightz.eth/feed/atom",
            "https://mirror.xyz/mintventures.eth/feed/atom",
            "https://mirror.xyz/missberri.eth/feed/atom",
            "https://mirror.xyz/mitchworz.eth/feed/atom",
            "https://mirror.xyz/mnhsu.eth/feed/atom",
            "https://mirror.xyz/mogician.eth/feed/atom",
            "https://mirror.xyz/momoswap.eth/feed/atom",
            "https://mirror.xyz/msfew.eth/feed/atom",
            "https://mirror.xyz/natashajuliakim.eth/feed/atom",
            "https://mirror.xyz/nbblockchain.eth/feed/atom",
            "https://mirror.xyz/nicoholo.eth/feed/atom",
            "https://mirror.xyz/nikkor.eth/feed/atom",
            "https://mirror.xyz/nikokvcs.eth/feed/atom",
            "https://mirror.xyz/nmkmn.eth/feed/atom",
            "https://mirror.xyz/nnimrodd.eth/feed/atom",
            "https://mirror.xyz/nomadlab.eth/feed/atom",
            "https://mirror.xyz/oic.eth/feed/atom",
            "https://mirror.xyz/ollieraps.eth/feed/atom",
            "https://mirror.xyz/onekiss.eth/feed/atom",
            "https://mirror.xyz/orangex.eth/feed/atom",
            "https://mirror.xyz/owoowo.eth/feed/atom",
            "https://mirror.xyz/owwwo.eth/feed/atom",
            "https://mirror.xyz/pactcollective.eth/feed/atom",
            "https://mirror.xyz/pagedao.eth/feed/atom",
            "https://mirror.xyz/pandapool.eth/feed/atom",
            "https://mirror.xyz/pangeadao.eth/feed/atom",
            "https://mirror.xyz/paulfinneyx.eth/feed/atom",
            "https://mirror.xyz/paymahn.eth/feed/atom",
            "https://mirror.xyz/payusnomind.eth/feed/atom",
            "https://mirror.xyz/penny777.eth/feed/atom",
            "https://mirror.xyz/peopleweb.eth/feed/atom",
            "https://mirror.xyz/peterleeb.eth/feed/atom",
            "https://mirror.xyz/pfeffunit.eth/feed/atom",
            "https://mirror.xyz/philippowis.eth/feed/atom",
            "https://mirror.xyz/phyrexia.eth/feed/atom",
            "https://mirror.xyz/picometaverse.eth/feed/atom",
            "https://mirror.xyz/primed2d.eth/feed/atom",
            "https://mirror.xyz/product.seedao.eth/feed/atom",
            "https://mirror.xyz/promisesk.eth/feed/atom",
            "https://mirror.xyz/purposeunknown.eth/feed/atom",
            "https://mirror.xyz/qiaodong.eth/feed/atom",
            "https://mirror.xyz/qinhaoyi.eth/feed/atom",
            "https://mirror.xyz/qiwihui.eth/feed/atom",
            "https://mirror.xyz/raccooncrypto.eth/feed/atom",
            "https://mirror.xyz/rahat.eth/feed/atom",
            "https://mirror.xyz/ranbuta.eth/feed/atom",
            "https://mirror.xyz/ravers.eth/feed/atom",
            "https://mirror.xyz/rayzzz.eth/feed/atom",
            "https://mirror.xyz/rcpw.eth/feed/atom",
            "https://mirror.xyz/readmore.eth/feed/atom",
            "https://mirror.xyz/rhian.eth/feed/atom",
            "https://mirror.xyz/rhizomedao.eth/feed/atom",
            "https://mirror.xyz/rohanda.eth/feed/atom",
            "https://mirror.xyz/ryangtanaka.eth/feed/atom",
            "https://mirror.xyz/ryguy.eth/feed/atom",
            "https://mirror.xyz/samegg.eth/feed/atom",
            "https://mirror.xyz/samhysell.eth/feed/atom",
            "https://mirror.xyz/sanmazi.eth/feed/atom",
            "https://mirror.xyz/saoge.eth/feed/atom",
            "https://mirror.xyz/sartoshi.eth/feed/atom",
            "https://mirror.xyz/scienceopen.eth/feed/atom",
            "https://mirror.xyz/scottmartinez.eth/feed/atom",
            "https://mirror.xyz/seener.eth/feed/atom",
            "https://mirror.xyz/seerlabs.eth/feed/atom",
            "https://mirror.xyz/serenayu.eth/feed/atom",
            "https://mirror.xyz/shenxianju.eth/feed/atom",
            "https://mirror.xyz/shibdao.eth/feed/atom",
            "https://mirror.xyz/shitcoindaily.eth/feed/atom",
            "https://mirror.xyz/shiyuan.eth/feed/atom",
            "https://mirror.xyz/shot.eth/feed/atom",
            "https://mirror.xyz/shremhouse.eth/feed/atom",
            "https://mirror.xyz/shreyjain.eth/feed/atom",
            "https://mirror.xyz/shrimpwen.eth/feed/atom",
            "https://mirror.xyz/silhouette114.eth/feed/atom",
            "https://mirror.xyz/sissixin.eth/feed/atom",
            "https://mirror.xyz/sleepy0x13.eth/feed/atom",
            "https://mirror.xyz/snapfingers.eth/feed/atom",
            "https://mirror.xyz/snapfingersdao.eth/feed/atom",
            "https://mirror.xyz/spatio.eth/feed/atom",
            "https://mirror.xyz/spf.eth/feed/atom",
            "https://mirror.xyz/stormg.eth/feed/atom",
            "https://mirror.xyz/stough.eth/feed/atom",
            "https://mirror.xyz/sunnizy.eth/feed/atom",
            "https://mirror.xyz/superogers.eth/feed/atom",
            "https://mirror.xyz/supreet.eth/feed/atom",
            "https://mirror.xyz/susheen.eth/feed/atom",
            "https://mirror.xyz/suzuha.eth/feed/atom",
            "https://mirror.xyz/svenpanda.eth/feed/atom",
            "https://mirror.xyz/swap123.eth/feed/atom",
            "https://mirror.xyz/syan.eth/feed/atom",
            "https://mirror.xyz/teji.eth/feed/atom",
            "https://mirror.xyz/terrycao.eth/feed/atom",
            "https://mirror.xyz/thefringe.eth/feed/atom",
            "https://mirror.xyz/themeaganloyst.eth/feed/atom",
            "https://mirror.xyz/therealsean.eth/feed/atom",
            "https://mirror.xyz/theweb3.eth/feed/atom",
            "https://mirror.xyz/tian7.eth/feed/atom",
            "https://mirror.xyz/tianshenxiafan.eth/feed/atom",
            "https://mirror.xyz/timnotjim.eth/feed/atom",
            "https://mirror.xyz/tmacmax.eth/feed/atom",
            "https://mirror.xyz/toddz.eth/feed/atom",
            "https://mirror.xyz/tomborgers.eth/feed/atom",
            "https://mirror.xyz/tomu.eth/feed/atom",
            "https://mirror.xyz/tookmymoney.eth/feed/atom",
            "https://mirror.xyz/toptour.eth/feed/atom",
            "https://mirror.xyz/totlsota.eth/feed/atom",
            "https://mirror.xyz/tpwallet.eth/feed/atom",
            "https://mirror.xyz/turfnft.eth/feed/atom",
            "https://mirror.xyz/twodam.eth/feed/atom",
            "https://mirror.xyz/typto.eth/feed/atom",
            "https://mirror.xyz/unemeta.eth/feed/atom",
            "https://mirror.xyz/vatalikbuterin.eth/feed/atom",
            "https://mirror.xyz/verite.eth/feed/atom",
            "https://mirror.xyz/viveca.eth/feed/atom",
            "https://mirror.xyz/vniu.eth/feed/atom",
            "https://mirror.xyz/wandaoliver.eth/feed/atom",
            "https://mirror.xyz/wangzhan.eth/feed/atom",
            "https://mirror.xyz/warpsound.eth/feed/atom",
            "https://mirror.xyz/watchensee.eth/feed/atom",
            "https://mirror.xyz/wenbrand.eth/feed/atom",
            "https://mirror.xyz/wherefi.eth/feed/atom",
            "https://mirror.xyz/wildchina.eth/feed/atom",
            "https://mirror.xyz/windyhill.eth/feed/atom",
            "https://mirror.xyz/winnow.eth/feed/atom",
            "https://mirror.xyz/wong2.eth/feed/atom",
            "https://mirror.xyz/wuque.eth/feed/atom",
            "https://mirror.xyz/x2y2.eth/feed/atom",
            "https://mirror.xyz/xch168.eth/feed/atom",
            "https://mirror.xyz/xdaipunk.eth/feed/atom",
            "https://mirror.xyz/xiangcai.eth/feed/atom",
            "https://mirror.xyz/xing824.eth/feed/atom",
            "https://mirror.xyz/xunfa.eth/feed/atom",
            "https://mirror.xyz/xxzzx.eth/feed/atom",
            "https://mirror.xyz/y4000.eth/feed/atom",
            "https://mirror.xyz/yanzu.eth/feed/atom",
            "https://mirror.xyz/yesheng.eth/feed/atom",
            "https://mirror.xyz/yewlne.eth/feed/atom",
            "https://mirror.xyz/yingsu.eth/feed/atom",
            "https://mirror.xyz/yond.eth/feed/atom",
            "https://mirror.xyz/yongxuan18.eth/feed/atom",
            "https://mirror.xyz/yourairdrop.eth/feed/atom",
            "https://mirror.xyz/yufly.eth/feed/atom",
            "https://mirror.xyz/yunzi.eth/feed/atom",
            "https://mirror.xyz/zachmiller.eth/feed/atom",
            "https://mirror.xyz/zainkhan.eth/feed/atom",
            "https://mirror.xyz/zephyrzj.eth/feed/atom",
            "https://mirror.xyz/zlexdl.eth/feed/atom",
            "https://mirror.xyz/zoroo.eth/feed/atom",
            "https://superrare.mirror.xyz/feed/atom",
            "https://syndicate.mirror.xyz/feed/atom",
            "https://the-looking-glass.mirror.xyz/feed/atom",
            "https://theblockchainsocialist.mirror.xyz/feed/atom",
            "https://thedaoist.mirror.xyz/feed/atom",
            "https://waterandmusic.mirror.xyz/feed/atom",
            "https://wong2.mirror.xyz/feed/atom",
            "https://x.mirror.xyz/feed/atom",
            "https://yup.mirror.xyz/feed/atom",
            "https://rsshub.app/jike/topic/58412cc399a0b50010877f8e",
            "https://rsshub.app/jike/topic/55e02198dcef9f0e00d7b3c3",
            "https://rsshub.app/jike/topic/5738965b6628391200809ff1",
            "https://mirror.xyz/0x31d61b448700D321536FF36A2cd299a1dea14CA2/feed/atom",
            "https://mirror.xyz/tannhauser2049.eth/feed/atom",
        ],
        "filters": [
            {
                "in_seconds": 3600 * 24 * 2,
            },
        ],
    },
    "mirror_chinese": {
        "limit": 2000,
        "urls": [
            "https://github.com/RoCry/arweave-tracker/releases/download/latest/posts.feed.json",
        ],
        "filters": [
            {
                "in_seconds": 3600 * 12,
            },
            {
                "title": "\p{Han}{2,}",
            },
        ],
    },
    "mirror": {
        "limit": 4000,
        "urls": [
            "https://github.com/RoCry/arweave-tracker/releases/download/latest/posts.feed.tiny.json",
        ],
        "filters": [
            {
                "in_seconds": 3600 * 12,
            },
        ],
    },
    "chainfeeds": {
        "limit": 2000,
        "opml": "https://raw.githubusercontent.com/chainfeeds/RSSAggregatorforWeb3/main/RAW.opml",
        "filters": [
            {
                "in_seconds": 3600 * 12,
            },
        ],
    },
}


def get_recipes(prefer_submirror=True) -> [dict]:
    recipes = {}
    for name, recipe in _recipes.items():
        for sub_name, r in _fulfill_opml_recipe(name, recipe).items():
            recipes[sub_name] = r
    if prefer_submirror:
        for recipe in recipes.values():
            _transform_to_submirror(recipe)
    return recipes


def _transform_to_submirror(r: dict):
    for i, u in enumerate(r["urls"]):
        r["urls"][i] = _transform_url_to_submirror(u)


def _transform_url_to_submirror(u: str) -> str:
    from urllib.parse import urlparse
    o = urlparse(u)
    if not o.path.endswith("/feed/atom"):
        return u
    if not o.hostname.endswith("mirror.xyz"):
        return u
    return u.replace("mirror.xyz", "submirror.xyz").rstrip("/feed/atom")


def test_transform_url_to_submirror():
    assert _transform_url_to_submirror(
        "https://mirror.xyz/0xBE4fde70B16d2dD454Fa8434E1A01131b90D2880/feed/atom") == "https://submirror.xyz/0xBE4fde70B16d2dD454Fa8434E1A01131b90D2880"
    assert _transform_url_to_submirror("https://dev.mirror.xyz/feed/atom") == "https://dev.submirror.xyz"
    assert _transform_url_to_submirror("https://optoutpod.com/blog/feed") == "https://optoutpod.com/blog/feed"
    assert _transform_url_to_submirror("https://rocry.com/feed/atom") == "https://rocry.com/feed/atom"


# change the recipe with opml url to multi recipes
def _fulfill_opml_recipe(name: str, recipe: dict) -> dict:
    if "opml" not in recipe:
        return {name: recipe}

    result = listparser.parse(recipe["opml"])
    del recipe["opml"]

    feeds = {}
    for f in result.feeds:
        categories = (
            ["uncategorized"]
            if not f.categories
            else reduce(operator.concat, f.categories)
        )
        for c in categories:
            feeds[c] = feeds.get(c, []) + [f.url]

    results = {}
    all_urls = set()
    for key, urls in feeds.items():
        r = recipe.copy()
        r["urls"] = urls
        all_urls.update(urls)
        results[f"{name}_{key}"] = r

    r = recipe.copy()
    r["urls"] = list(all_urls)
    results[name] = r
    return results
